export const CHANGE_TAB = 'CHANGE_TAB';

export const CHANGE_TOOL_TYPE = 'CHANGE_TOOL_TYPE';
export const CHANGE_TOOL_SIZE = 'CHANGE_TOOL_SIZE';
export const CHANGE_TOOL_COLOR = 'CHANGE_TOOL_COLOR';

export const CHANGE_CANVAS_OPACITY = 'CHANGE_CANVAS_OPACITY';
export const CHANGE_CANVAS_COLOR = 'CHANGE_CANVAS_COLOR';
export const CHANGE_CANVAS_ZOOM = 'CHANGE_CANVAS_ZOOM';

